version: "3"

services:
  dev-shopping-app-db:
    image: postgres:alpine3.18
    expose:
      - "5432"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DEV_DJANGO_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEV_DJANGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEV_DJANGO_DATABASE_NAME}
    volumes:
      - dev-shopping-app-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DEV_DJANGO_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dev-shopping-app-network
    restart: always

  dev-shopping-app-be:
    build: .
    environment:
      DEV_DJANGO_DATABASE_USER: ${DEV_DJANGO_DATABASE_USER}
      DEV_DJANGO_DATABASE_PASSWORD: ${DEV_DJANGO_DATABASE_PASSWORD}
      DEV_DJANGO_DATABASE_NAME: ${DEV_DJANGO_DATABASE_NAME}
      DEV_DJANGO_KEY: ${DEV_DJANGO_KEY}
    command:
      python manage.py runserver 0.0.0.0:7001 --settings=shoppingapp.settings.dev_settings
    expose:
      - "7001"
    ports:
      - "7001:7001"
    depends_on:
      dev-shopping-app-db:
        condition: service_healthy
    networks:
      - dev-shopping-app-network
    restart: always

networks:
  dev-shopping-app-network:
    driver: bridge

volumes:
  dev-shopping-app-db-data:
    external: false
